// https://finalfantasy.fandom.com/wiki/Final_Fantasy_VIII_Triple_Triad_cards
module.exports = {
	tier1: [ // monsters, < 7, total power < 14
		{tier: 1, id:'001', north: 1, east: 4, south: 1, west: 5, name: 'Geezard', element: null},
		{tier: 1, id:'002', north: 5, east: 1, south: 1, west: 3, name: 'Funguar', element: null},
		{tier: 1, id:'003', north: 1, east: 3, south: 3, west: 5, name: 'Bite Bug', element: null},
		{tier: 1, id:'004', north: 6, east: 1, south: 1, west: 2, name: 'Red Bat', element: null},
		{tier: 1, id:'005', north: 2, east: 3, south: 1, west: 5, name: 'Blobra', element: null},
		{tier: 1, id:'006', north: 2, east: 1, south: 4, west: 4, name: 'Gayla', element: null},
		{tier: 1, id:'007', north: 1, east: 5, south: 4, west: 1, name: 'Gesper', element: null},
		{tier: 1, id:'008', north: 3, east: 5, south: 2, west: 1, name: 'Fastitocalon-F', element: null},
		{tier: 1, id:'009', north: 2, east: 1, south: 6, west: 1, name: 'Blood Soul', element: null},
		{tier: 1, id:'010', north: 4, east: 2, south: 4, west: 3, name: 'Caterchipillar', element: null},
		{tier: 1, id:'011', north: 2, east: 1, south: 2, west: 6, name: 'Cockatrice', element: null},
	],
	tier2: [ // monsters, < 8, total power < 16
		{tier: 2, id:'012', north: 7, east: 1, south: 3, west: 1, name: 'Grat', element: null},
		{tier: 2, id:'013', north: 6, east: 2, south: 2, west: 3, name: 'Buel', element: null},
		{tier: 2, id:'014', north: 5, east: 3, south: 3, west: 4, name: 'Mesmerize', element: null},
		{tier: 2, id:'015', north: 6, east: 1, south: 4, west: 3, name: 'Glacial Eye', element: null},
		{tier: 2, id:'016', north: 3, east: 4, south: 5, west: 3, name: 'Belhelmel', element: null},
		{tier: 2, id:'017', north: 5, east: 3, south: 2, west: 5, name: 'Thrustaevis', element: null},
		{tier: 2, id:'018', north: 5, east: 1, south: 3, west: 5, name: 'Anacondaur', element: null},
		{tier: 2, id:'019', north: 5, east: 2, south: 5, west: 2, name: 'Creeps', element: null},
		{tier: 2, id:'020', north: 4, east: 4, south: 5, west: 2, name: 'Grendel', element: null},
		{tier: 2, id:'021', north: 3, east: 2, south: 1, west: 7, name: 'Jelleye', element: null},
		{tier: 2, id:'022', north: 5, east: 2, south: 5, west: 3, name: 'Grand Mantis', element: null},
	],
	tier3: [ // monsters, < 8, total power < 18
		{tier: 3, id:'023', north: 6, east: 6, south: 3, west: 2, name: 'Forbidden', element: null},
		{tier: 3, id:'024', north: 6, east: 3, south: 1, west: 6, name: 'Armadodo', element: null},
		{tier: 3, id:'025', north: 3, east: 5, south: 5, west: 5, name: 'Tri-Face', element: null},
		{tier: 3, id:'026', north: 7, east: 5, south: 1, west: 3, name: 'Fastitocalon', element: null},
		{tier: 3, id:'027', north: 7, east: 1, south: 5, west: 3, name: 'Snow Lion', element: null},
		{tier: 3, id:'028', north: 5, east: 6, south: 3, west: 3, name: 'Ochu', element: null},
		{tier: 3, id:'029', north: 5, east: 6, south: 2, west: 4, name: 'SAM08G', element: null},
		{tier: 3, id:'030', north: 4, east: 4, south: 7, west: 2, name: 'Death Claw', element: null},
		{tier: 3, id:'031', north: 6, east: 2, south: 6, west: 3, name: 'Cactuar', element: null},
		{tier: 3, id:'032', north: 3, east: 6, south: 4, west: 4, name: 'Tonberry', element: null},
		{tier: 3, id:'033', north: 7, east: 2, south: 3, west: 5, name: 'Abyss Worm', element: null},
	],
	tier4: [ // monsters, < 8, total power < 21
		{tier: 4, id:'034', north: 2, east: 3, south: 6, west: 7, name: 'Turtapod', element: null},
		{tier: 4, id:'035', north: 6, east: 5, south: 4, west: 5, name: 'Vysage', element: null},
		{tier: 4, id:'036', north: 4, east: 6, south: 2, west: 7, name: 'T-Rexaur', element: null},
		{tier: 4, id:'037', north: 2, east: 7, south: 6, west: 3, name: 'Bomb', element: null},
		{tier: 4, id:'038', north: 1, east: 6, south: 4, west: 7, name: 'Blitz', element: null},
		{tier: 4, id:'039', north: 7, east: 3, south: 1, west: 6, name: 'Wendigo', element: null},
		{tier: 4, id:'040', north: 7, east: 4, south: 4, west: 4, name: 'Torama', element: null},
		{tier: 4, id:'041', north: 3, east: 7, south: 3, west: 6, name: 'Imp', element: null},
		{tier: 4, id:'042', north: 6, east: 2, south: 7, west: 3, name: 'Blue Dragon', element: null},
		{tier: 4, id:'043', north: 4, east: 5, south: 5, west: 6, name: 'Adamantoise', element: null},
		{tier: 4, id:'044', north: 7, east: 5, south: 4, west: 3, name: 'Hexadragon', element: null},
	],
	tier5: [ // monsters, total power < 24
		{tier: 5, id:'045', north: 6, east: 5, south: 6, west: 5, name: 'Iron Giant', element: null},
		{tier: 5, id:'046', north: 3, east: 6, south: 5, west: 7, name: 'Behemoth', element: null},
		{tier: 5, id:'047', north: 7, east: 6, south: 5, west: 3, name: 'Chimera', element: null},
		{tier: 5, id:'048', north: 3, east: 10, south: 2, west: 1, name: 'PuPu', element: null},
		{tier: 5, id:'049', north: 6, east: 2, south: 6, west: 7, name: 'Elastoid', element: null},
		{tier: 5, id:'050', north: 5, east: 5, south: 7, west: 4, name: 'GIM47N', element: null},
		{tier: 5, id:'051', north: 7, east: 7, south: 4, west: 2, name: 'Malboro', element: null},
		{tier: 5, id:'052', north: 7, east: 2, south: 7, west: 4, name: 'Ruby Dragon', element: null},
		{tier: 5, id:'053', north: 5, east: 3, south: 7, west: 6, name: 'Elnoyle', element: null},
		{tier: 5, id:'054', north: 4, east: 6, south: 7, west: 4, name: 'Tonberry King', element: null},
		{tier: 5, id:'055', north: 6, east: 6, south: 2, west: 7, name: 'Biggs & Wedge', element: null},
	],
	tier6: [ // bosses, total power < 24
		{tier: 6, id:'056', north: 2, east: 8, south: 8, west: 4, name: 'Fujin & Raijin', element: null},
		{tier: 6, id:'057', north: 7, east: 8, south: 3, west: 4, name: 'Elvoret', element: null},
		{tier: 6, id:'058', north: 4, east: 8, south: 7, west: 3, name: 'X-ATM092', element: null},
		{tier: 6, id:'059', north: 7, east: 2, south: 8, west: 5, name: 'Granaldo', element: null},
		{tier: 6, id:'060', north: 1, east: 8, south: 8, west: 3, name: 'Gerogero', element: null},
		{tier: 6, id:'061', north: 8, east: 2, south: 8, west: 2, name: 'Iguion', element: null},
		{tier: 6, id:'062', north: 6, east: 8, south: 4, west: 5, name: 'Abadon', element: null},
		{tier: 6, id:'063', north: 4, east: 8, south: 5, west: 6, name: 'Trauma', element: null},
		{tier: 6, id:'064', north: 1, east: 8, south: 4, west: 8, name: 'Oilboyle', element: null},
		{tier: 6, id:'065', north: 6, east: 5, south: 8, west: 4, name: 'Shumi Tribe', element: null},
		{tier: 6, id:'066', north: 7, east: 5, south: 8, west: 1, name: 'Krysta', element: null},
	],
	tier7: [ // bosses, total power < 26
		{tier: 7, id:'067', north: 8, east: 4, south: 4, west: 8, name: 'Propagator', element: null},
		{tier: 7, id:'068', north: 8, east: 8, south: 4, west: 4, name: 'Jumbo Cactuar', element: null},
		{tier: 7, id:'069', north: 8, east: 5, south: 2, west: 8, name: 'Tri-Point', element: null},
		{tier: 7, id:'070', north: 5, east: 6, south: 6, west: 8, name: 'Gargantua', element: null},
		{tier: 7, id:'071', north: 8, east: 6, south: 7, west: 3, name: 'Mobile Type 8', element: null},
		{tier: 7, id:'072', north: 8, east: 3, south: 5, west: 8, name: 'Sphinxara', element: null},
		{tier: 7, id:'073', north: 8, east: 8, south: 5, west: 4, name: 'Tiamat', element: null},
		{tier: 7, id:'074', north: 5, east: 7, south: 8, west: 5, name: 'BGH251F2', element: null},
		{tier: 7, id:'075', north: 6, east: 8, south: 4, west: 7, name: 'Red Giant', element: null},
		{tier: 7, id:'076', north: 1, east: 8, south: 7, west: 7, name: 'Catoblepas', element: null},
		{tier: 7, id:'077', north: 7, east: 7, south: 2, west: 8, name: 'Ultima Weapon', element: null},
	],
	tier8: [ // guardian forces, total power < 26
		{tier: 8, id:'078', north: 4, east: 4, south: 8, west: 9, name: 'Fat Chocobo', element: null},
		{tier: 8, id:'079', north: 9, east: 6, south: 7, west: 3, name: 'Angelo', element: null},
		{tier: 8, id:'080', north: 3, east: 7, south: 9, west: 6, name: 'Gilgamesh', element: null},
		{tier: 8, id:'081', north: 9, east: 3, south: 9, west: 2, name: 'MiniMog', element: null},
		{tier: 8, id:'082', north: 9, east: 4, south: 8, west: 4, name: 'Chicobo', element: null},
		{tier: 8, id:'083', north: 2, east: 9, south: 9, west: 4, name: 'Quezacotl', element: null},
		{tier: 8, id:'084', north: 6, east: 7, south: 4, west: 9, name: 'Shiva', element: null},
		{tier: 8, id:'085', north: 9, east: 6, south: 2, west: 8, name: 'Ifrit', element: null},
		{tier: 8, id:'086', north: 8, east: 9, south: 6, west: 2, name: 'Siren', element: null},
		{tier: 8, id:'087', north: 5, east: 1, south: 9, west: 9, name: 'Sacred', element: null},
		{tier: 8, id:'088', north: 9, east: 5, south: 2, west: 9, name: 'Minotaur', element: null},
	],
	tier9: [ // guardian forces, A (10), total power < 27
		{tier: 9, id:'089', north: 8, east: 4, south: 10, west: 4, name: 'Carbuncle', element: null},
		{tier: 9, id:'090', north: 5, east: 10, south: 8, west: 3, name: 'Diablos', element: null},
		{tier: 9, id:'091', north: 7, east: 10, south: 1, west: 7, name: 'Leviathan', element: null},
		{tier: 9, id:'092', north: 8, east: 10, south: 3, west: 5, name: 'Odin', element: null},
		{tier: 9, id:'093', north: 10, east: 1, south: 7, west: 7, name: 'Pandemona', element: null},
		{tier: 9, id:'094', north: 7, east: 4, south: 6, west: 10, name: 'Cerberus', element: null},
		{tier: 9, id:'095', north: 9, east: 10, south: 4, west: 2, name: 'Alexander', element: null},
		{tier: 9, id:'096', north: 7, east: 2, south: 7, west: 10, name: 'Phoenix', element: null},
		{tier: 9, id:'097', north: 10, east: 8, south: 2, west: 6, name: 'Bahamut', element: null},
		{tier: 9, id:'098', north: 3, east: 1, south: 10, west: 10, name: 'Doomtrain', element: null},
		{tier: 9, id:'099', north: 4, east: 4, south: 9, west: 10, name: 'Eden', element: null},
	],
	tier10: [ // characters, A (10), total power < 30
		{tier: 10, id:'100', north: 10, east: 7, south: 2, west: 8, name: 'Ward', element: null},
		{tier: 10, id:'101', north: 6, east: 7, south: 6, west: 10, name: 'Kiros', element: null},
		{tier: 10, id:'102', north: 5, east: 10, south: 3, west: 9, name: 'Laguna', element: null},
		{tier: 10, id:'103', north: 10, east: 8, south: 6, west: 4, name: 'Selphie', element: null},
		{tier: 10, id:'104', north: 9, east: 6, south: 10, west: 2, name: 'Quistis', element: null},
		{tier: 10, id:'105', north: 2, east: 6, south: 9, west: 10, name: 'Irvine', element: null},
		{tier: 10, id:'106', north: 8, east: 5, south: 10, west: 6, name: 'Zell', element: null},
		{tier: 10, id:'107', north: 4, east: 10, south: 2, west: 10, name: 'Rinoa', element: null},
		{tier: 10, id:'108', north: 10, east: 10, south: 3, west: 3, name: 'Edea', element: null},
		{tier: 10, id:'109', north: 6, east: 9, south: 10, west: 4, name: 'Seifer', element: null},
		{tier: 10, id:'110', north: 10, east: 4, south: 6, west: 9, name: 'Squall', element: null},
	]
};
